### Word Embedding Techniques using Embedding Layer in Keras

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

2025-03-10 11:09:57.108978: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-03-10 11:09:57.120657: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1741584297.134675    3219 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1741584297.138944    3219 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-03-10 11:09:57.151442: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instr

In [2]:
##sentences
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size = 10000

### One Hot Representation

In [5]:
onehot_repr=[one_hot(words,voc_size) for words in sent]
print(onehot_repr)

[[2009, 1334, 3299, 2048], [2009, 1334, 3299, 3678], [2009, 8913, 3299, 620], [6689, 7840, 7640, 6189, 2563], [6689, 7840, 7640, 6189, 4033], [5857, 2009, 9837, 3299, 6975], [8632, 8961, 3558, 6189]]


### Word Embedding Representation

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_lengths = 8
embedded_docs = pad_sequences(onehot_repr,padding='pre',maxlen=sent_lengths)
print(embedded_docs)

[[   0    0    0    0 2009 1334 3299 2048]
 [   0    0    0    0 2009 1334 3299 3678]
 [   0    0    0    0 2009 8913 3299  620]
 [   0    0    0 6689 7840 7640 6189 2563]
 [   0    0    0 6689 7840 7640 6189 4033]
 [   0    0    0 5857 2009 9837 3299 6975]
 [   0    0    0    0 8632 8961 3558 6189]]


In [9]:
dim = 10 

In [14]:
model = Sequential()
model.add(Embedding(voc_size,10,
                        input_shape=(sent_lengths,)))
model.compile('adam','mse')

/home/harry/Documents/Code/Data_Science/DeepLearning/.venv_tf/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [15]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step
[[[ 0.02455162 -0.04208952  0.03691773  0.03234137 -0.01906139
   -0.00425322 -0.02108437  0.01569773 -0.01741485  0.01721331]
  [ 0.02455162 -0.04208952  0.03691773  0.03234137 -0.01906139
   -0.00425322 -0.02108437  0.01569773 -0.01741485  0.01721331]
  [ 0.02455162 -0.04208952  0.03691773  0.03234137 -0.01906139
   -0.00425322 -0.02108437  0.01569773 -0.01741485  0.01721331]
  [ 0.02455162 -0.04208952  0.03691773  0.03234137 -0.01906139
   -0.00425322 -0.02108437  0.01569773 -0.01741485  0.01721331]
  [-0.03295907  0.04746456  0.04935533  0.04906409 -0.01191705
   -0.04247999  0.01825486  0.01099847 -0.01241    -0.04169365]
  [-0.01072608 -0.00704109 -0.01761365  0.04478123  0.00530035
   -0.04490566  0.00206035 -0.02410109  0.0034412   0.02165388]
  [-0.00373683 -0.01569643  0.0179863   0.02532487  0.03604079
    0.01585818 -0.02891216 -0.03304874 -0.04980648 -0.02267152]
  [ 0.01679695  0.03820128 -0.01582075 -0.01974483 -0.00308989
   -0.0068

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0, 2009, 1334, 3299, 2048], dtype=int32)

In [18]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step
[[ 0.02455162 -0.04208952  0.03691773  0.03234137 -0.01906139 -0.00425322
  -0.02108437  0.01569773 -0.01741485  0.01721331]
 [ 0.02455162 -0.04208952  0.03691773  0.03234137 -0.01906139 -0.00425322
  -0.02108437  0.01569773 -0.01741485  0.01721331]
 [ 0.02455162 -0.04208952  0.03691773  0.03234137 -0.01906139 -0.00425322
  -0.02108437  0.01569773 -0.01741485  0.01721331]
 [ 0.02455162 -0.04208952  0.03691773  0.03234137 -0.01906139 -0.00425322
  -0.02108437  0.01569773 -0.01741485  0.01721331]
 [-0.03295907  0.04746456  0.04935533  0.04906409 -0.01191705 -0.04247999
   0.01825486  0.01099847 -0.01241    -0.04169365]
 [-0.01072608 -0.00704109 -0.01761365  0.04478123  0.00530035 -0.04490566
   0.00206035 -0.02410109  0.0034412   0.02165388]
 [-0.00373683 -0.01569643  0.0179863   0.02532487  0.03604079  0.01585818
  -0.02891216 -0.03304874 -0.04980648 -0.02267152]
 [ 0.01679695  0.03820128 -0.01582075 -0.01974483 -0.00308989 -0.0068607
   0.02147243 